[[ACCOUNTS]]
address = "r9NcytRxC1CX1vERGn9HGR2Bwbuo6tGX1h"
desc = "Issuer account for Trustless Payments"

[[CURRENCIES]]
code = "TRLS"
issuer = "r9NcytRxC1CX1vERGn9HGR2Bwbuo6tGX1h"
name = "Trustless Token"
desc = "TRLS powers the Trustless escrow system — Honor Through Automation."
icon = "https://donkekleone.github.io/trls.png"
